Repository mash-up-kr/DHC-iOS, pull requests merged in 2025-06, with the labels that each got.

#4 [Feature] TCA 템플릿 생성 및 샘플코드 작성
  DHC-iOS.xcodeproj/project.pbxproj
  DHC-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DHC-iOS/ContentView.swift
  DHC-iOS/DHC_iOSApp.swift
  install_template.sh
  template/DHComposableArchitecture/Dependency.xctemplate/TemplateIcon.png
  template/DHComposableArchitecture/Dependency.xctemplate/TemplateInfo.plist
  template/DHComposableArchitecture/Dependency.xctemplate/___FILEBASENAME___.swift
  template/DHComposableArchitecture/Feature.xctemplate/TemplateIcon.png
  template/DHComposableArchitecture/Feature.xctemplate/TemplateInfo.plist
  template/DHComposableArchitecture/Feature.xctemplate/___FILEBASENAME___Reducer.swift
  template/DHComposableArchitecture/Feature.xctemplate/___FILEBASENAME___View.swift
  template/DHComposableArchitecture/Reducer.xctemplate/TemplateIcon.png
  template/DHComposableArchitecture/Reducer.xctemplate/TemplateInfo.plist
  template/DHComposableArchitecture/Reducer.xctemplate/___FILEBASENAME___Reducer.swift
Labels: Feature, 혜린

#7 IOS-23 Button 컴포넌트 구현
  Project/App/Resources/Color.xcassets/Neutral/400.colorset/Contents.json
  Project/App/Resources/Color.xcassets/Neutral/500.colorset/Contents.json
  Project/App/Resources/Color.xcassets/Neutral/600.colorset/Contents.json
  Project/App/Sources/Design System/Asset/Color.swift
  Project/App/Sources/Design System/View/Button/DHCButton.swift
  Project/App/Sources/Design System/View/Button/FloatingButton.swift
  Project/App/Sources/Design System/View/Button/dummy.swift
Labels: Design

#10 IOS-28 추가된 버튼 컴포넌트를 구현해요
  Project/App/Resources/Image.xcassets/Contents.json
  Project/App/Resources/Image.xcassets/check.imageset/Contents.json
  Project/App/Resources/Image.xcassets/check.imageset/check.svg
  Project/App/Sources/Design System/Asset/Typography.swift
  Project/App/Sources/Design System/View/Button/CTAButton.swift
  Project/App/Sources/Design System/View/Button/CheckButton.swift
  Project/App/Sources/Design System/View/Button/FloatingButton.swift
  Project/App/Sources/Design System/View/Button/SelectableButton.swift
  Project/App/Sources/Design System/View/CheckMark/CheckMark.swift
  Project/App/Sources/Util/Extension/ImageResource+.swift
Labels: Design

#11 IOS-29 NavigationBar와 DatePicker를 구현해요
  Project/App/Resources/Image.xcassets/Chevron/Contents.json
  Project/App/Resources/Image.xcassets/Chevron/left.imageset/Contents.json
  Project/App/Resources/Image.xcassets/Chevron/left.imageset/chevron-left.svg
  Project/App/Sources/Design System/View/Datepicker/DHCDatePicker.swift
  Project/App/Sources/Design System/View/NavigationBar/DHCNavigationBar.swift
Labels: Design

#12 IOS-32 마이페이지 뷰 UI를 구현해요.
  Project/App/Project.swift
  Project/App/Resources/Assets.xcassets/icon/signOut.imageset/Contents.json
  Project/App/Resources/Assets.xcassets/icon/signOut.imageset/signOut.pdf
  Project/App/Sources/Design System/Asset/Typography.swift
  Project/App/Sources/Design System/View/Gradient/RadialGradientBackground.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MyPage/Components/BirthdayInfoView.swift
  Project/App/Sources/Feature/MyPage/Components/CategoryCardView.swift
  Project/App/Sources/Feature/MyPage/Components/FortuneInfoCardView.swift
  Project/App/Sources/Feature/MyPage/Components/SettingListRowView.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+.swift
Labels: Feature

#13 [IOS-30] 개인정보 입력 UI를 구현해요
  Project/App/Sources/Design System/Asset/Color.swift
  Project/App/Sources/Design System/View/Button/CTAButton.swift
  Project/App/Sources/Design System/View/Button/SelectableButton.swift
  Project/App/Sources/Design System/View/CheckMark/CheckMark.swift
  Project/App/Sources/Design System/View/IntroInfo/IntroInfoView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/BirthTime/BirthTimeInputReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/BirthTime/BirthTimeInputView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Birthday/BirthdayInputReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Birthday/BirthdayInputView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Gender/SelectGenderReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Gender/SelectGenderView.swift
  Project/App/Sources/Util/Extension/Foundation+/Date+.swift
  Project/App/Sources/Util/Extension/SwiftUI+/ColorResource+.swift
  Project/App/Sources/Util/Extension/SwiftUI+/ImageResource+.swift
Labels: Feature

#18 IOS-40 사용 중인 써드파티 라이브러리들을 dynamic framework로 변경
  Tuist/Package.swift
Labels: 세진, Infra

#19 IOS-41 프로젝트 이름을 Flifin으로 변경해요.
  Project/App/Project.swift
  Project/App/Sources/App/FlifinApp.swift
  Project/App/Sources/App/RootReducer.swift
  Project/App/Sources/App/RootView.swift
  Project/App/Sources/Design System/Asset/Color.swift
  Project/App/Sources/Design System/Asset/Typography.swift
  Project/App/Sources/Design System/View/Button/CTAButton.swift
  Project/App/Sources/Design System/View/Button/CheckButton.swift
  Project/App/Sources/Design System/View/Button/FloatingButton.swift
  Project/App/Sources/Design System/View/Button/SelectableButton.swift
  Project/App/Sources/Design System/View/CheckMark/CheckMark.swift
  Project/App/Sources/Design System/View/Datepicker/DHCDatePicker.swift
  Project/App/Sources/Design System/View/Gradient/RadialGradientBackground.swift
  Project/App/Sources/Design System/View/IntroInfo/IntroTitleView.swift
  Project/App/Sources/Design System/View/NavigationBar/DHCNavigationBar.swift
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Feature/Home/NotificationPermissionReducer.swift
  Project/App/Sources/Feature/Home/NotificationPermissionView.swift
  Project/App/Sources/Feature/MainTab/MainTabReducer.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MainTab/TabKind.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusReducer.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusView.swift
  Project/App/Sources/Feature/MyPage/Components/BirthdayInfoView.swift
  Project/App/Sources/Feature/MyPage/Components/CategoryCardView.swift
  Project/App/Sources/Feature/MyPage/Components/FortuneInfoCardView.swift
  Project/App/Sources/Feature/MyPage/Components/SettingListRowView.swift
  Project/App/Sources/Feature/MyPage/MyPageReducer.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Project/App/Sources/Feature/Onboarding/Intro/ServiceExplanation/Component/IntroInfoView.swift
  Project/App/Sources/Feature/Onboarding/Intro/ServiceExplanation/ServiceExplanationReducer.swift
  Project/App/Sources/Feature/Onboarding/Intro/ServiceExplanation/ServiceExplanationView.swift
  Project/App/Sources/Feature/Onboarding/OnboardingReducer.swift
  Project/App/Sources/Feature/Onboarding/OnboardingView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/BirthTime/BirthTimeInputReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/BirthTime/BirthTimeInputView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Birthday/BirthdayInputReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Birthday/BirthdayInputView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Gender/SelectGenderReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Gender/SelectGenderView.swift
  Project/App/Sources/Network/NetworkManager.swift
  Project/App/Sources/Network/NetworkManagerError.swift
  Project/App/Sources/Network/NetworkResponse.swift
  Project/App/Sources/Network/RequestTarget.swift
  Project/App/Sources/Services/Keychain/KeychainClient.swift
  Project/App/Sources/Services/Keychain/KeychainError.swift
  Project/App/Sources/Services/Keychain/KeychainService.swift
  Project/App/Sources/Services/UserNotification/UserNotificationClient.swift
  Project/App/Sources/Util/DeviceID/DeviceIDManager.swift
  Project/App/Sources/Util/Extension/Foundation+/Date+.swift
  Project/App/Sources/Util/Extension/SwiftUI+/ColorResource+.swift
  Project/App/Sources/Util/Extension/SwiftUI+/ImageResource+.swift
  Workspace.swift
Labels: 세진, Infra

#20 IOS-39 캘린더를 제외한 미션 현황 뷰 UI를 구현해요.
  Project/App/Resources/Image.xcassets/moneyWithWings.imageset/Contents.json
  Project/App/Resources/Image.xcassets/moneyWithWings.imageset/moneyWithWings.pdf
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MissionStatus/Components/MissionSummaryView.swift
  Project/App/Sources/Feature/MissionStatus/Components/SpendChartAnnotationView.swift
  Project/App/Sources/Feature/MissionStatus/Components/SpendChartCardView.swift
  Project/App/Sources/Feature/MissionStatus/Components/SpendChartView.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusView.swift
  Project/App/Sources/Util/Extension/SwiftUI+/ColorResource+.swift
Labels: Feature, 세진

#21 [IOS-37] 온보딩(카드 뒤집기 화면) UI를 구현해요
  Project/App/Resources/Color.xcassets/Etc/#414BAE.colorset/Contents.json
  Project/App/Resources/Color.xcassets/Etc/#D7E1EE.colorset/Contents.json
  Project/App/Resources/Color.xcassets/Etc/Contents.json
  Project/App/Sources/Design System/Asset/Gradient/LinearGradient.swift
  Project/App/Sources/Design System/View/Badge/BadgeView.swift
  Project/App/Sources/Design System/View/Fortune/FortuneCardView.swift
  Project/App/Sources/Design System/View/Fortune/FortuneScoreView.swift
  Project/App/Sources/Design System/View/Fortune/FortuneView.swift
  Project/App/Sources/Design System/View/Shape/BottomRoundedInvertedTriangle.swift
  Project/App/Sources/Feature/MyPage/Components/FortuneInfoCardView.swift
  Project/App/Sources/Feature/Onboarding/Intro/FortunePickExample/Component/OnboardingTooltipView.swift
  Project/App/Sources/Feature/Onboarding/Intro/FortunePickExample/FortunePickExampleReducer.swift
  Project/App/Sources/Feature/Onboarding/Intro/FortunePickExample/FortunePickExampleView.swift
  Project/App/Sources/Util/Extension/SwiftUI+/View+.swift
Labels: Feature, 혜린

#23 IOS-44 미션 현황 탭에 쓰이는 캘린더 뷰를 구현해요.
  Project/App/Resources/Image.xcassets/Chevron/right.imageset/Contents.json
  Project/App/Resources/Image.xcassets/Chevron/right.imageset/right.pdf
  Project/App/Sources/Feature/MissionStatus/Components/CalendarCardView.swift
  Project/App/Sources/Feature/MissionStatus/Components/MissionSummaryView.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusView.swift
  Project/App/Sources/Util/Extension/Foundation+/Date+.swift
Labels: Feature, 세진

#28 IOS-33 MyPage 정보 불러오는 API를 연결해요.
  Project/App/Project.swift
  Project/App/Sources/Design System/View/CategoryCard/CategoryCardView.swift
  Project/App/Sources/Feature/MainTab/MainTabReducer.swift
  Project/App/Sources/Feature/MyPage/Components/FortuneInfoCardView.swift
  Project/App/Sources/Feature/MyPage/MyPageReducer.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Project/App/Sources/Models/MyPage/MyPageInfo.swift
  Project/App/Sources/Network/NetworkManagerError.swift
  Project/App/Sources/Network/NetworkResponse.swift
  Project/App/Sources/Network/RequestTarget.swift
  Project/App/Sources/Services/MyPageService/DTO/MyPageDTO.swift
  Project/App/Sources/Services/MyPageService/MyPageAPI.swift
  Project/App/Sources/Services/MyPageService/MyPageClient.swift
  Project/App/Sources/Util/DateFormatter/DateFormatterCache.swift
  Project/App/Sources/Util/Lock/MutexLock.swift
Labels: Feature, 세진

#22 IOS-27 Mission Item과 Badge 컴포넌트를 구현해요
  Project/App/Resources/Color.xcassets/Badge/Contents.json
  Project/App/Resources/Color.xcassets/Badge/MissionLevel/Contents.json
  Project/App/Resources/Color.xcassets/Badge/MissionLevel/levelEasy.colorset/Contents.json
  Project/App/Resources/Color.xcassets/Badge/MissionLevel/levelHard.colorset/Contents.json
  Project/App/Sources/Design System/View/Badge/Badge.swift
  Project/App/Sources/Design System/View/Badge/DHCBadge.swift
  Project/App/Sources/Design System/View/Mission/DailyMissionItemView.swift
  Project/App/Sources/Design System/View/Mission/MissionItem.swift
  Project/App/Sources/Design System/View/Mission/PinnedMissionItemView.swift
Labels: Feature, 유빈
