Repository mash-up-kr/DHC-iOS, pull requests merged in 2025-07, with the labels that each got.

#14 [IOS-25] Bottom Sheet 컴포넌트를 구현해요
  Project/App/Sources/Design System/View/BottomSheet/DHCBottomSheet.swift
  Project/App/Sources/Design System/View/BottomSheet/DHCBottomSheetContent.swift
Labels: 유빈, Design

#29 IOS-53 2,3 탭의 네비게이션 바 구성
  Project/App/Sources/Design System/View/NavigationBar/LargeNavigationTitleView.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusView.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
Labels: Feature, 세진

#30 IOS-52 탈퇴 로직을 구현해요.
  Project/App/Sources/App/RootReducer.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertReducer.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertView.swift
  Project/App/Sources/Feature/MyPage/MyPageReducer.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Project/App/Sources/Services/MyPageService/MyPageAPI.swift
  Project/App/Sources/Services/MyPageService/MyPageClient.swift
Labels: Feature, 세진

#31 IOS-54 로딩 스피너를 추가해요.
  Project/App/Resources/Color.xcassets/Etc/#2D2D2D.colorset/Contents.json
  Project/App/Sources/Design System/View/Loading/DHCLoadingSpinner.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertReducer.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertView.swift
  Project/App/Sources/Util/Extension/SwiftUI+/View+Loading.swift
Labels: Feature, 세진

#35 [IOS-55] 온보딩 관련 API를 연동해요
  Project/App/Sources/App/RootReducer.swift
  Project/App/Sources/Design System/View/CategoryCard/CategoryCardView.swift
  Project/App/Sources/Feature/MyPage/MyPageReducer.swift
  Project/App/Sources/Feature/Onboarding/OnboardingReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Birthday/BirthdayInputReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Category/SelectCategoryReducer.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Category/SelectCategoryView.swift
  Project/App/Sources/Feature/Onboarding/SignUp/Gender/SelectGenderReducer.swift
  Project/App/Sources/Models/SignUp/CategoryInfo.swift
  Project/App/Sources/Models/SignUp/Domain/MissionCategory.swift
  Project/App/Sources/Models/SignUp/Request/RegisterUserRequest.swift
  Project/App/Sources/Models/SignUp/Response/MissionCategoryDTO.swift
  Project/App/Sources/Models/SignUp/Response/UserIDDTO.swift
  Project/App/Sources/Network/APIEventLogger.swift
  Project/App/Sources/Network/NetworkManager.swift
  Project/App/Sources/Network/RequestTarget.swift
  Project/App/Sources/Services/DHCAPISerivce/MyPageService/DTO/MyPageDTO.swift
  Project/App/Sources/Services/DHCAPISerivce/MyPageService/MyPageAPI.swift
  Project/App/Sources/Services/DHCAPISerivce/MyPageService/MyPageClient.swift
  Project/App/Sources/Services/DHCAPISerivce/SignUpService/SignUpAPI.swift
  Project/App/Sources/Services/DHCAPISerivce/SignUpService/SignUpClient.swift
  Project/App/Sources/Services/DeviceID/DeviceIDManager.swift
  Project/App/Sources/Services/UserManager/UserManager.swift
  Project/App/Sources/Util/Extension/Foundation+/Data+.swift
Labels: Feature, 혜린

#39 IOS-61 리포트 탭의 소비 분석 API를 연결해요.
  Project/App/Sources/Feature/MainTab/MainTabReducer.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MainTab/TabKind.swift
  Project/App/Sources/Feature/MissionStatus/Components/SpendChartView.swift
  Project/App/Sources/Feature/MissionStatus/MissionStatusReducer.swift
  Project/App/Sources/Feature/MissionStatus/ReportReducer.swift
  Project/App/Sources/Feature/MissionStatus/ReportView.swift
  Project/App/Sources/Models/Report/ReportInfo.swift
  Project/App/Sources/Services/ReportService/DTO/ReportDTO.swift
  Project/App/Sources/Services/ReportService/ReportAPI.swift
  Project/App/Sources/Services/ReportService/ReportClient.swift
Labels: Feature, 세진

#44 [IOS-43] 미션 확인 화면 UI를 구현해요
  Project/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Project/App/Resources/Assets.xcassets/AppIcon.appiconset/appIcon.png
  Project/App/Resources/Color.xcassets/Etc/#020202.colorset/Contents.json
  Project/App/Sources/Feature/Home/MissionList/MissionListReducer.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
  Project/App/Sources/Feature/Onboarding/Intro/MissionExample/MissionExampleReducer.swift
  Project/App/Sources/Feature/Onboarding/Intro/MissionExample/MissionExampleView.swift
  Project/App/Sources/Feature/Onboarding/OnboardingView.swift
  Project/App/Sources/Models/Home/HomeInfo.swift
  Project/App/Sources/Util/Extension/Foundation+/Date+.swift
Labels: Feature, 혜린

#47 IOS-70 자잘한 UI 수정
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertView.swift
Labels: Feature, 세진

#48 [IOS-67] 매일 첫 Home 진입 시 FortuneLoadingCompleteView 보여주는 로직을 구현해요
  Project/App/Sources/App/RootReducer.swift
  Project/App/Sources/Feature/Home/FortuneLoading/LoadingComplete/FortuneLoadingCompleteReducer.swift
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Feature/MainTab/MainTabReducer.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MyPage/AppResetAlert/AppResetAlertReducer.swift
  Project/App/Sources/Services/DHCAPISerivce/HomeService/DTO/HomeDTO.swift
  Project/App/Sources/Services/LaunchManager/LaunchManager.swift
Labels: Feature, 혜린

#49 [IOS-77] 태어난 시간 "잘 모르겠어요" 선택 시 가입되지 않는 현상을 수정해요
  Project/App/Sources/Feature/MyPage/Components/BirthdayInfoView.swift
  Project/App/Sources/Feature/MyPage/MyPageReducer.swift
  Project/App/Sources/Models/MyPage/MyPageInfo.swift
  Project/App/Sources/Models/SignUp/Request/RegisterUserRequest.swift
  Project/App/Sources/Services/DHCAPISerivce/MyPageService/DTO/MyPageDTO.swift
  Project/App/Sources/Services/DHCAPISerivce/SignUpService/SignUpClient.swift
Labels: Bug, 혜린

#50 [IOS-76] FortuneLoadingCompleteView 계속 뜨는 현상을 수정해요
  Project/App/Sources/Feature/Home/HomeReducer.swift
Labels: Bug, 혜린

#53 [IOS-87] 스플래시 로띠 파일을 교체해요
  Project/App/Resources/File/splash.json
Labels: 혜린, Design

#54 [IOS-83] 프로젝트에 사용되는 영상 리소스 볼륨을 제어해요
  Project/App/Sources/Design System/Asset/BundleResource.swift
  Project/App/Sources/Feature/Home/FortuneLoading/Loading/FortuneLoadingView.swift
  Project/App/Sources/Feature/Onboarding/LoopingVideoPlayer.swift
  Project/App/Sources/Feature/Onboarding/OnboardingView.swift
Labels: Bug, 혜린

#56 [IOS-79] 인트로 02, 03 화면 UI를 수정해요
  Project/App/Resources/Image.xcassets/fortuneCardShadow.imageset/Contents.json
  Project/App/Resources/Image.xcassets/fortuneCardShadow.imageset/FortuneCard-Shadow.svg
  Project/App/Sources/Design System/View/Fortune/FortuneCard/FlippableFortuneCardView.swift
  Project/App/Sources/Design System/View/Fortune/FortuneScoreView.swift
  Project/App/Sources/Design System/View/Fortune/FortuneView.swift
  Project/App/Sources/Feature/Home/FortuneDetail/FortuneDetailView.swift
  Project/App/Sources/Feature/Home/FortuneLoading/LoadingComplete/FortuneLoadingCompleteView.swift
  Project/App/Sources/Feature/MainTab/MainTabView.swift
  Project/App/Sources/Feature/MissionStatus/ReportView.swift
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Project/App/Sources/Feature/Onboarding/Intro/FortunePickExample/FortunePickExampleView.swift
  Project/App/Sources/Models/Home/FortuneDetail/Domain/FortuneDetail.swift
Labels: 혜린, Design

#57 [IOS-85] 금전운 상세 페이지 DTO 구조를 변경해요
  Project/App/Sources/Models/Home/FortuneDetail/Response/FortuneDetailDTO.swift
Labels: Bug, 혜린

#59 [IOS-72] '오늘 미션 끝내기' 버튼 overlay로 구현 및 그라디언트를 적용해요
  Project/App/Sources/Design System/View/Button/FloatingButton.swift
  Project/App/Sources/Design System/View/Gradient/LinearGradient.swift
  Project/App/Sources/Design System/View/Gradient/RadialGradientBackground.swift
  Project/App/Sources/Feature/Home/HomeView.swift
Labels: 혜린, Design

#60 [IOS-86] 일일 절약 금액 API Response를 반영해요
  Project/App/Sources/Feature/Home/Component/HomePopup.swift
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Feature/MainTab/MainTabReducer.swift
  Project/App/Sources/Models/Home/HomeInfo.swift
  Project/App/Sources/Network/NetworkResponse.swift
  Project/App/Sources/Services/DHCAPISerivce/HomeService/DTO/HomeDTO.swift
  Project/App/Sources/Services/DHCAPISerivce/HomeService/DTO/TodayMissionDoneDTO.swift
  Project/App/Sources/Services/DHCAPISerivce/HomeService/Home/HomeAPIClient.swift
  Project/App/Sources/Util/Extension/Foundation+/String.swift
Labels: Feature, 혜린

#61 [IOS-92] HomeView UI 수정사항을 반영해요
  Project/App/Sources/Design System/View/Badge/DHCBadge.swift
  Project/App/Sources/Design System/View/Mission/MissionItem.swift
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
Labels: 혜린, Design

#63 IOS-93 리포트 탭 QA
  Project/App/Sources/Feature/MyPage/MyPageView.swift
  Project/App/Sources/Feature/Report/CalendarMissionCompletionStage.swift
  Project/App/Sources/Feature/Report/Components/CalendarCardView.swift
  Project/App/Sources/Feature/Report/Components/MissionSummaryView.swift
  Project/App/Sources/Feature/Report/Components/SpendChartAnnotationView.swift
  Project/App/Sources/Feature/Report/Components/SpendChartCardView.swift
  Project/App/Sources/Feature/Report/Components/SpendChartView.swift
  Project/App/Sources/Feature/Report/ReportReducer.swift
  Project/App/Sources/Feature/Report/ReportView.swift
Labels: 세진, QA

#62 IOS-89 오늘 미션이 끝난 경우 미션 리스트를 disable 처리해요
  Project/App/Sources/Design System/View/Badge/DHCBadge.swift
  Project/App/Sources/Design System/View/Mission/DailyMissionItemView.swift
  Project/App/Sources/Design System/View/Mission/MissionItem.swift
  Project/App/Sources/Design System/View/Mission/PinnedMissionItemView.swift
  Project/App/Sources/Feature/Home/Component/HomePopup.swift
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListReducer.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
  Project/App/Sources/Feature/Onboarding/Intro/MissionExample/MissionExampleReducer.swift
Labels: Feature, 유빈

#66 [IOS-97] Info.plist에 버전을 추가하고 버전을 하나 올려요
  Project/App/Project.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
Labels: Feature, 혜린

#67 IOS-99 리포트 뷰 데이터 채우기 및 코드 개선
  Project/App/Sources/Feature/Report/Components/CalendarCardView.swift
  Project/App/Sources/Feature/Report/Components/SpendChartView.swift
  Project/App/Sources/Feature/Report/ReportReducer.swift
  Project/App/Sources/Feature/Report/ReportView.swift
  Project/App/Sources/Models/Report/ReportInfo.swift
  Project/App/Sources/Services/ReportService/DTO/ReportDTO.swift
  Project/App/Sources/Services/ReportService/ReportAPI.swift
  Project/App/Sources/Services/ReportService/ReportClient.swift
  Project/App/Sources/Util/View/DeviceShakeViewModifier.swift
Labels: Feature, 세진, QA

#68 [IOS-101] 홈 화면 카드 뷰를 수정해요
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Models/Home/HomeInfo.swift
  Project/App/Sources/Services/DHCAPISerivce/HomeService/DTO/HomeDTO.swift
Labels: Bug, 혜린

#69 [IOS-100] 앱 사용 시 음악 꺼지는 이슈를 수정해요
  Project/App/Sources/Feature/Onboarding/LoopingVideoPlayer.swift
Labels: Bug, 혜린

#73 IOS-75 미션 완료 버튼을 누른 경우 토스트 메세지를 띄워요 🍞
  Project/App/Sources/Feature/Home/HomeReducer.swift
  Project/App/Sources/Feature/Home/HomeView.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListReducer.swift
  Project/App/Sources/Util/Constants/ToastMessages.swift
Labels: Feature, 유빈

#72 [IOS-104] HomeView의 swipe UI를 개선해요
  Project/App/Sources/Feature/Home/FortuneDetail/FortuneDetailView.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListReducer.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
  Project/App/Sources/Feature/Home/MissionList/SwipeableMissionItemView.swift
  Project/App/Sources/Feature/Onboarding/Intro/MissionExample/MissionExampleReducer.swift
Labels: Feature, 혜린

#76 [IOS-109] 버전 업데이트(1.0.2)
  Project/App/Project.swift
  Project/App/Resources/Image.xcassets/Celebration.imageset/Contents.json
Labels: Chore, 혜린

#77 [IOS-110] 온보딩 카드 이미지를 수정해요
  Project/App/Resources/Image/fortuneCardFrontDefaultView.png
  Project/App/Sources/Feature/Home/FortuneDetail/FortuneDetailView.swift
  Project/App/Sources/Feature/Home/MissionList/MissionListView.swift
  Project/App/Sources/Feature/Onboarding/Intro/ServiceExplanation/Component/IntroInfoView.swift
Labels: Chore, 혜린

#78 [IOS-111] 버전 업데이트(1.0.3)
  Project/App/Project.swift
Labels: Chore, 혜린
